spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
share:
  location: ./shares # 共享文件存放位置